### ISSUE TITLE
Keep black version pinned

### ISSUE THREAD

**Issue by dconathan** [greenbone/autohooks-plugin-black#135]
I know this is mostly black's fault because they still don't have a non-prerelease release, but can we keep the version of black pinned until they do?  Otherwise, trying to use autohooks-plugins-black with pipenv leads to error messages like this:

```
ERROR: Could not find a version that matches black<=21.6b0,==21.6b0,>=20.8b1
```

Right now my only solution is the pin `autohooks-plugin-black` to the version where black was pinned to a single version.

**Comment by bjoernricks** [comment]
Hi, I suppose it is best to pin the version of black directly in your project and not in autohooks-plugin-black. Could you check if that fixes your problem?

**Comment by dconathan** [comment]
Nope, that is exactly what I tried.  My Pipfile contains:

```
autohooks-plugin-black = "*"
black = "==20.8b1"
```

When I run `pipenv install` (or `update`, etc.), I get:

```
There are incompatible versions in the resolved dependencies:
  black==21.7b0 (from -r /var/folders/dx/5px6y8lx60bfvv692_49dq1m0000gn/T/pipenvds8hv0jbrequirements/pipenv-p8poahbm-constraints.txt (line 4))
  black<=21.7b0,>=20.8b1 (from autohooks-plugin-black==21.7.1->-r /var/folders/dx/5px6y8lx60bfvv692_49dq1m0000gn/T/pipenvds8hv0jbrequirements/pipenv-p8poahbm-constraints.txt (line 8))
  ```
  
  Right now my only solution is to have something like this in my Pipfile (pin to old version of the plugin back when a single version of black was pinned):
  
```
autohooks-plugin-black = "==21.6.0"
black = "==20.8b1"
```

**Comment by bjoernricks** [comment]
For me that seems to be an issue with the pipenv dependency resolver. Of course this problem would not occur if black gets a real release finally...
